const authUser = ()=>
    {
        try {
            
        } catch (error) {
            
        }
    }